--
-- Name: books; Type: TABLE;
--

CREATE TABLE if not EXISTS books
(
    id            bigint NOT NULL,
    updated_at    date   NOT NULL,
    created_at    date   NOT NULL,
    tag_id        bigint,
    name          text   NOT NULL,
    owner_id      bigint NOT NULL,
    link_to_cover text
);

alter table books
    alter column id add generated by default as identity;

--
-- Name: book_files; Type: TABLE;
--

CREATE TABLE if not exists book_files
(
    id           bigint NOT NULL,
    name         text   NOT NULL,
    uploaded_at  date   NOT NULL,
    book_id      bigint NOT NULL,
    google_drive_id text   NOT NULL
);

alter table book_files
    alter column id add generated by default as identity;

--
-- Name: request_statuses; Type: TABLE;
--

CREATE TABLE if not exists request_statuses
(
    id   bigint NOT NULL,
    name text   NOT NULL
);

alter table request_statuses
    alter column id add generated by default as identity;

--
-- Name: roles; Type: TABLE;
--

CREATE TABLE if not exists roles
(
    id   bigint NOT NULL,
    name text   NOT NULL
);

alter table roles
    alter column id add generated by default as identity;

--
-- Name: tags; Type: TABLE;
--

CREATE TABLE if not exists tags
(
    id       bigint NOT NULL,
    name     text   NOT NULL,
    main_tag bigint
);

alter table tags
    alter column id add generated by default as identity;

--
-- Name: users; Type: TABLE;
--

CREATE TABLE if not exists users
(
    id         bigint NOT NULL,
    role_id    bigint NOT NULL,
    username   text   NOT NULL,
    email      text   NOT NULL,
    password   text   NOT NULL,
    provider   text   NOT NULL
);

alter table users
    alter column id add generated by default as identity;

--
-- Name: reports; Type: TABLE;
--

CREATE TABLE if not exists reports
(
    id           bigint NOT NULL,
    created_at   date   NOT NULL,
    text         text   NOT NULL,
    user_id      bigint NOT NULL,
    status       bigint NOT NULL,
    moderator_id bigint,
    book_id      bigint NOT NULL
);

alter table reports
    alter column id add generated by default as identity;

--
-- Name: help_requests; Type: TABLE;
--

CREATE TABLE if not exists help_requests
(
    id           bigint NOT NULL,
    created_at   date   NOT NULL,
    text         text   NOT NULL,
    email        text   NOT NULL,
    status       bigint NOT NULL,
    moderator_id bigint
);

alter table help_requests
    alter column id add generated by default as identity;

--
-- Name: comments; Type: TABLE;
--

CREATE TABLE if not exists comments
(
    id         bigint NOT NULL,
    created_at date   NOT NULL,
    text       text   NOT NULL,
    user_id    bigint NOT NULL,
    book_id    bigint NOT NULL
);

alter table comments
    alter column id add generated by default as identity;

--
-- Name: personal_libraries; Type: TABLE;
--

CREATE TABLE if not exists personal_libraries
(
    user_id bigint NOT NULL,
    book_id bigint NOT NULL
);

--
-- Type: CONSTRAINTs;
--

ALTER TABLE ONLY book_files
    ADD CONSTRAINT book_files_pk PRIMARY KEY (id);

ALTER TABLE ONLY books
    ADD CONSTRAINT books_pk PRIMARY KEY (id);

ALTER TABLE ONLY request_statuses
    ADD CONSTRAINT request_statuses_pk PRIMARY KEY (id);

ALTER TABLE ONLY roles
    ADD CONSTRAINT roles_pk PRIMARY KEY (id);

ALTER TABLE ONLY tags
    ADD CONSTRAINT tags_pk PRIMARY KEY (id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pk PRIMARY KEY (id);

ALTER TABLE ONLY reports
    ADD CONSTRAINT reports_pk PRIMARY KEY (id);

ALTER TABLE ONLY help_requests
    ADD CONSTRAINT help_requests_pk PRIMARY KEY (id);

ALTER TABLE ONLY comments
    ADD CONSTRAINT comments_pk PRIMARY KEY (id);

--
-- Type: FK CONSTRAINTs;
--

ALTER TABLE ONLY book_files
    ADD CONSTRAINT book_file_books_id_fk FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE ONLY books
    ADD CONSTRAINT books_fk_tag FOREIGN KEY (tag_id) REFERENCES tags (id);

ALTER TABLE ONLY books
    ADD CONSTRAINT books_fk_owner FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE ONLY users
    ADD CONSTRAINT user_fk_role FOREIGN KEY (role_id) REFERENCES roles (id);


ALTER TABLE ONLY reports
    ADD CONSTRAINT reports_fk_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE ONLY reports
    ADD CONSTRAINT reports_fk_status FOREIGN KEY (status) REFERENCES request_statuses (id);

ALTER TABLE ONLY reports
    ADD CONSTRAINT reports_fk_moderator FOREIGN KEY (moderator_id) REFERENCES users (id);

ALTER TABLE ONLY reports
    ADD CONSTRAINT reports_fk_book FOREIGN KEY (book_id) REFERENCES books (id);


ALTER TABLE ONLY help_requests
    ADD CONSTRAINT help_requests_fk_status FOREIGN KEY (status) REFERENCES request_statuses (id);

ALTER TABLE ONLY help_requests
    ADD CONSTRAINT help_requests_fk_moderator FOREIGN KEY (moderator_id) REFERENCES users (id);


ALTER TABLE ONLY comments
    ADD CONSTRAINT comments_fk_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE ONLY comments
    ADD CONSTRAINT comments_fk_book FOREIGN KEY (book_id) REFERENCES books (id);


ALTER TABLE ONLY personal_libraries
    ADD CONSTRAINT personal_libraries_fk_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE ONLY personal_libraries
    ADD CONSTRAINT personal_libraries_fk_book FOREIGN KEY (book_id) REFERENCES books (id);

--
-- Type: TABLEs DATA;
--

insert into request_statuses (id, name)
values (default, 'Not processed');
insert into request_statuses (id, name)
values (default, 'Confirmed');
insert into request_statuses (id, name)
values (default, 'Declined');

insert into roles (id, name)
values (default, 'user');
insert into roles (id, name)
values (default, 'moderator');

insert into tags (id, name)
values (default, 'all');

insert into users (id, role_id, username, email, password, provider)
values (default, 2, 'admin', 'admin@admin.com',
        '$2a$10$iWOIpv08YdHeiemEEOqm/O3QHvYtjdBn6azEIipixYe7hoA6rRhxa', 'local');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'Володимир Лис, “Століття Якова”', 1, 'https://i.grenka.ua/shop/1/4/670/stolittya-yakova_0d7.jpg');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'Дарина Гнатко, “Притулок семи вітрів”', 1, 'https://i.grenka.ua/shop/1/10/505/pritulok-semi-vitriv_e51.jpg');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'Ірена Карпа, «Як виходити заміж стільки разів, скільки захочете»', 1, 'https://i.grenka.ua/shop/1/10/803/yak-vikhoditi-zamizh-stilki-raziv-skilki-zakhochete_725.jpg');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'Максим Бутченко, «Жінка в темряві. Зелений клин»', 1, 'https://i.grenka.ua/shop/1/11/4/zhinka-v-temryavi-zelenij-klin_404.jpg');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'Стівен Кінг, «Довга Хода»', 1, 'https://i.grenka.ua/shop/1/12/928/dovga-khoda_367.jpg');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'В. Е. Шваб, «Незриме життя Адді Лярю»', 1, 'https://i.grenka.ua/shop/1/12/929/nezrime-zhittya-addi-lyaryu_998.jpg');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'Юрай Червенак, «Богатир. Книга 1: Сталеве жезло»', 1, 'https://i.grenka.ua/shop/1/12/933/bogatir-kniga-1-staleve-zhezlo_fa1.jpg');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'Анна Беннінг, «Вихрь 2. Девушка, которая прорвалась сквозь время»', 1, 'https://i.grenka.ua/shop/1/12/467/vikhr-2-devushka-kotoraya-prorvalas-skvoz-vremya_af5.jpg');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'Кен Лю, «Прихована дівчина та інші оповідання»', 1, 'https://i.grenka.ua/shop/1/12/690/prikhovana-divchina-ta-inshi-opovidannya_47f.jpg');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'Діна Бухольц, «Неофіційна кулінарна книга Гаррі Поттера»', 1, 'https://i.grenka.ua/shop/1/12/899/neofitsijna-kulinarna-kniga-garri-pottera_6fd.jpg');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'Михайло Жирохов, «Зброя Перемоги»', 1, 'https://i.grenka.ua/shop/1/12/917/zbroya-peremogi_1c1.jpg');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'Ірина Тараненко, Марта Лешак, «Книга-мандрівка. Незалежні»', 1, 'https://i.grenka.ua/shop/1/12/929/kniga-mandrivka-nezalezhni_2c4.jpg');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'Том Шиппі, «Сміючись і помру: про життя і смерть видатних вікінгів»', 1, 'https://i.grenka.ua/shop/1/12/931/smiyuchis-i-pomru-pro-zhittya-i-smert-vidatnikh-vikingiv_093.jpg');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'Дмитро Муравський, «Через війну»', 1, 'https://i.grenka.ua/shop/1/9/787/cherez-vijnu_885.jpg');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'Шелбі Мег`юрін, «Змія і голуб»', 1, 'https://i.grenka.ua/shop/1/12/929/zmiya-i-golub_7db.png');

insert into books (id, updated_at, created_at, tag_id, name, owner_id, link_to_cover)
values (default, now(), now(), 1, 'Сергій Плохій, «Ядерне безумство. Історія Карибської кризи»', 1, 'https://i.grenka.ua/shop/1/12/907/yaderne-bezumstvo-istoriya-karibskoyi-krizi_a86.jpg');
